---
- name: Configure Ansible Automation Platform | controller_credential_input_sources
  hosts: "{{ env | default('dev') }}"
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Include vars from vault | controller_credential_input_sources
      ansible.builtin.include_vars:
        file: "../vaults/{{ env }}.yml"
      tags:
        - always

  tasks:
    - name: Collect configurations | controller_credential_input_sources
      ansible.builtin.include_tasks:
        file: "configure_items.yml"
      vars:
        __configure_aap_dir: "{{ item['directory'] }}"
        __configure_aap_setting: "{{ item['name'] }}"
        __configure_var_name: "{{ item['default_attr'] }}"
        __configure_var_env_name: "{{ item['env_attr'] }}"
      loop: "{{ configuration_items }}"
      when:
        - item['name'] == 'controller_credential_input_sources'
      tags:
        - always

    - name: INCLUDE_ROLE | infra.aap_configuration.controller_credential_input_sources
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_credential_input_sources
      when:
        - controller_credential_input_sources is defined
        - controller_credential_input_sources | length > 0
      tags:
        - always
...
